### ISSUE TITLE
Add a Python (pypi) version of Maven Artifact Zip Directory Structure to build hook (and upload to pypi registry)

### ISSUE THREAD

**Issue by jimisola** [luftfartsverket/reqstool-python-hatch-plugin#14]
Relates to: https://github.com/luftfartsverket/reqstool-client/issues/111

For Java we create the zip file during `package`and attach it so that it is uploaded during `deploy`.
With hatch we have targets build and publish. We can create the zip file in build and/or publish so that it's uploaded to pypi in publish.

See: https://hatch.pypa.io/1.12/plugins/publisher/reference/#hatch.publish.plugin.interface.PublisherInterface

1. config in pyproject.toml
```toml
[tool.hatch.publish.publish_reqstool_zip_artifact]
dependencies = ["reqstool-python-hatch-plugin == <version>"]
# https://luftfartsverket.github.io/reqstool-java-maven-plugin/reqstool-java-maven-plugin/0.0.3/index.html#_configuration
requirementsAnnotationsFile
svcsAnnotationsFile
outputDirectory
datasetPath
failsafeReportsDir/surefireReportsDir
```

2. Implement a plugin with corresponding hook configuration

* https://github.com/luftfartsverket/reqstool-python-hatch-plugin/blob/main/src/reqstool_python_hatch_plugin/publish_hooks/publish_reqstool_zip_artifact.py

* Hook into `finalize` rather than `initialize` https://github.com/luftfartsverket/reqstool-python-hatch-plugin/blob/main/src/reqstool_python_hatch_plugin/build_hook/hook.py#L49

* `PLUGIN_NAME = "publish_reqstool_zip_artifact"`

Update docs for publish hook in README and AsciiDoc.

**Comment by jimisola** [comment]
Stub:

```python
import os
import zipfile
from hatchling.publish.plugin.interface import PublisherInterface
from dataclasses import field, dataclass
from typing import List

class ReqstoolZipArtifactPublisher(PublisherInterface):
    PLUGIN_NAME = 'publish_reqstool_zip_artifact'

    def publish(self, artifacts):
        config = self.config
        
        # Default values for paths

        # Fetch configuration from pyproject.toml or use default values
        requirements_annotations_file = config.get('requirements_annotations_file', "build/reqstool/annotations.yml")
        # ....
        
        
        # Define output ZIP file
        zipfile_name = os.path.join(output_directory, 'build_output.zip')

        # Create ZIP file
        with zipfile.ZipFile(zipfile_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
            # Add files to the ZIP archive
            if os.path.exists(requirements_annotations_file):
                zipf.write(requirements_annotations_file, os.path.basename(requirements_annotations_file))

            if os.path.exists(dataset_path):
                for root, _, files in os.walk(dataset_path):
                    for file in files:
                        file_path = os.path.join(root, file)
                        zipf.write(file_path, os.path.relpath(file_path, dataset_path))

            # Include junit report directory
            if os.path.exists(junit_reports_dir):
                for root, _, files in os.walk(junit_reports_dir):
                    for file in files:
                        file_path = os.path.join(root, file)
                        zipf.write(file_path, os.path.relpath(file_path, junit_reports_dir))

        print(f"ZIP file created: {zipfile_name}")
        return artifacts

```


```toml
[tool.hatch.publish.zip_publisher]
requirements_annotations_file = "path/to/requirements.yml"
svcs_annotations_file = "path/to/software_verification_cases.yml"
output_directory = "path/to/output"
dataset_path = "path/to/manual_verification_results.yml"
junit_reports_dir = "path/to/junit-reports"
```

**Comment by lfvjimisola** [comment]
Some changes will be made due to #13 and the decision with @lfvdavid to create zip in build hook

**Comment by lfvjimisola** [comment]
Check e.g. https://github.com/ofek/hatch-autorun/tree/master on how to write tests

**Comment by jimisola** [comment]
pypi and PEPs only allow for one sdist (tar.gz) so we have to either

1. make sure that the reqstools files are in the tar.gz sdist file (which they are, but depending on build system; hatchling, poetry etc, the layout may differ. Some sort of fixes reqstool index file pointing out the files is then needed similar to [reqstool_config.yml](https://github.com/luftfartsverket/reqstool-client/blob/main/src/reqstool/resources/schemas/v1/reqstool_config.schema.json)

2. using a separate package with additional suffix, i.e. mypackage will have sibling package mypackage-reqstool. however, the drawbacks are substantial with this solution:
  1. administration of to pypi projects for each actual projects
  2. how to assure atomic deploys, that both mypackage and sibling mypackage-reqstool are uploaded successfully at the same time
 
 
@lfvdavid @lfvkalle I reckon we need to go with option 1

**Comment by lfvdavid** [comment]
Agree with option 1.

Is it only one file? Had the impression it would be a dir containing the reqstool files.

In any case either 1. or 3.

1. is simple
3.  is more describing and follows the same format as the reqstool files such as ´software_verification_cases.yml´

**Comment by lfvjimisola** [comment]
So, final solution (which includes breaking changes):

1. the configuration of the plugin has changed
1. a reqstool_config.yml is added the sdist (which already includes all the reqstool files)
1. the sdist is uploaded as usual
